In [1]:
# read data set 'nba_2013.csv'
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsRegressor as nr
from sklearn.model_selection import train_test_split as tts
import math
# import data
data_path = 'nba_2013.csv'
df_nba = pd.read_csv(data_path)
df_nba.head()

,Rk,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,1,Quincy Acy,PF,22,TOR,29,342,15.9,0.632,0.027,...,15.6,14.7,0.7,0.4,1.1,0.157,-0.6,1.0,0.5,0.2
1,2,Jeff Adrien,PF,26,CHA,52,713,13.4,0.493,0.012,...,13.1,15.6,0.5,0.4,1.0,0.064,-2.9,-0.4,-3.3,-0.2
2,3,Arron Afflalo,SF,27,ORL,64,2307,13.0,0.527,0.265,...,12.1,22.5,1.5,0.5,2.0,0.042,-0.4,-1.9,-2.3,-0.2
3,4,Josh Akognon,PG,26,DAL,3,9,15.3,0.625,0.500,...,0.0,20.3,0.0,0.0,0.0,0.196,4.3,-4.9,-0.6,0.0
4,5,Cole Aldrich,C,24,TOT,45,388,11.1,0.563,0.000,...,20.6,12.7,0.1,0.4,0.6,0.070,-4.4,0.4,-3.9,-0.2

In [2]:
# sum how many nan in the data
df_nba.isnull().sum()

Rk        0
Player    0
Pos       0
Age       0
Tm        0
G         0
MP        0
PER       1
TS%       4
3PAr      4
FTr       4
ORB%      1
DRB%      1
TRB%      1
AST%      1
STL%      1
BLK%      1
TOV%      3
USG%      1
OWS       0
DWS       0
WS        0
WS/48     1
OBPM      0
DBPM      0
BPM       0
VORP      0
dtype: int64

In [3]:
# use mean method to imputate missing values
df_nba.fillna(df_nba.mean(), inplace = True)
df_nba.isnull().sum()

Rk        0
Player    0
Pos       0
Age       0
Tm        0
G         0
MP        0
PER       0
TS%       0
3PAr      0
FTr       0
ORB%      0
DRB%      0
TRB%      0
AST%      0
STL%      0
BLK%      0
TOV%      0
USG%      0
OWS       0
DWS       0
WS        0
WS/48     0
OBPM      0
DBPM      0
BPM       0
VORP      0
dtype: int64

In [4]:
# split data to training/testing data to 4:1, use several knn (k=5, k=sqrt(n), k=50) 
# models to predict player rank, evaluation matrics is mse
# set up the data to test and train
factor = df_nba[['Age','G', 'MP', 'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 
            'TRB%', 'AST%', 'STL%', 'BLK%','TOV%', 'USG%', 'OWS', 'DWS', 
            'WS', 'WS/48', 'OBPM', 'DBPM','BPM', 'VORP']]
predict = df_nba['Rk']
factor_train, factor_test, predict_train, predict_test = tts(factor, predict, test_size=0.2, random_state=0)

In [5]:
# define a function to test which knn is better
def fit_and_test(knn):
    knn_model = nr(n_neighbors = knn)
    knn_model.fit(factor_train, predict_train)
    result = knn_model.predict(factor_test)
    return (((result- predict_test) ** 2).sum()) / len(predict_test)

In [7]:
# test different knn
print("if knn = 2, mse = " + str(fit_and_test(5)))
print("if knn = square of n, mse = " + str(fit_and_test(int(math.sqrt(df_nba.shape[0])))))
print("if knn = 50, mse = " + str(fit_and_test(50)))

if knn = 2, mse = 21918.24904347826
if knn = square of n, mse = 19493.943963179092
if knn = 50, mse = 19494.240066086957